import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import typescript from 'rollup-plugin-typescript2';
import rust from "@wasm-tool/rollup-plugin-rust";

const path = require("path");
const banner =
  `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: 'index.ts',
  output: {
    file: path.resolve('../main.js'),
    sourcemap: 'inline',
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian'],
  plugins: [
    rust({
      inlineWasm: true
    }),
    nodeResolve({ browser: true }),
    commonjs(),
    typescript()
  ]
};