const path = require("path");
const webpack = require("webpack");
const WasmPackPlugin = require("@wasm-tool/wasm-pack-plugin");

const dist = path.resolve(__dirname, "dist");
const rustObsidianSlack = path.resolve("../rust/obsidian-slack");


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

module.exports = (env) => { 
  const isProduciton = env === "production";

  return {
    mode: "production",
    entry: {
      index: "./bootstrap.js"
    },
    output: {
      path: dist,
      filename: "main.js",
      library: {
        type: "commonjs2"
      }
    },
    watch: !isProduciton,
    target: ["web", "es2018"],
    stats: {
      logging: 'info',
    },
    devtool: isProduciton ? false : "inline-source-map",
    plugins: [
      new WasmPackPlugin({
        crateDirectory: rustObsidianSlack,
      }),
      new webpack.BannerPlugin(banner)
    ],
    experiments: {
      asyncWebAssembly: true
    }
  }
};